function ob --description 'Run ompui inside claudebox (pwd + agent + ~/.my-omp; internet, no LAN)'
    # Prefer a just-built flake result (DNS fix) over a stale home-manager install.
    set -l claudebox_bin
    if test -x $HOME/code/claudebox/result/bin/claudebox
        set claudebox_bin $HOME/code/claudebox/result/bin/claudebox
    else if command -q claudebox
        set claudebox_bin (command -v claudebox)
    else
        echo "ob: claudebox not on PATH (and no ~/code/claudebox/result)" >&2
        return 127
    end
    if not command -q bun
        echo "ob: bun not on PATH" >&2
        return 127
    end
    set -l agent /home/fipso/code/my-omp
    # This agent's config root (PI_CONFIG_DIR=.my-omp, set by src/bootstrap.ts) —
    # not the ~/.omp used by the stock `omp` CLI.
    set -l omp_dir $HOME/.my-omp
    set -l project (pwd -P)

    # Paths the stdio MCP servers in ~/.my-omp/agent/mcp.json need. They live outside
    # the agent tree, so --no-mount-home hides them and the spawn dies with ENOENT —
    # the server just shows up as "Transport closed". All ro: we only exec/read these.
    # NOTE: ~/.config/gcloud is the GCP application-default credential (a refresh
    # token). Anything running in the box can read it and act as you on GCP.
    # Still not covered (each needs a call you have to make deliberately):
    #   opnsense  also needs --lan-range 192.168.178.0/24 (drops the LAN block)
    #   blender   talks to 127.0.0.1 — loopback is blocked, no mount fixes it
    set -l mcp_dirs \
        $HOME/code/blazed-sh-sh \
        $HOME/code/gtm-mcp-stdio \
        $HOME/code/OPNSenseMCP \
        $HOME/.cache/pipx \
        $HOME/.config/gcloud

    if not test -f $agent/src/bootstrap.ts
        echo "ob: agent entry not found: $agent/src/bootstrap.ts" >&2
        return 1
    end

    set -l shell_mode 0
    set -l agent_argv
    set -l extra_mounts
    for a in $argv
        switch $a
            case --help -h
                echo "usage: ob [--shell|-s] [PATH...] [ompui-args...]"
                echo
                echo "Spawn ompui inside claudebox (gVisor + pasta)."
                echo "  mounts: \$PWD, $agent, ~/.my-omp, MCP server dirs (ro)"
                echo "  --no-mount-home  (home masked; only explicit mounts are visible RW)"
                echo "  internet: yes · LAN/private ranges: blocked"
                echo
                echo "  --shell, -s   open a shell in the box (cd to \$PWD) instead of ompui"
                echo "  PATH          any arg naming an existing file/dir is mounted rw at"
                echo "                the same path (suffix :ro for read-only) and is NOT"
                echo "                forwarded to ompui — e.g. ob /tmp/x ~/.config/omp"
                echo "  other args    forwarded to ompui (e.g. --mode auto, a prompt)"
                return 0
            case --shell -s
                set shell_mode 1
            case '*'
                # A bare arg that names something on disk is an extra mount; anything
                # else (flags, a prompt) still goes to ompui. An explicit :ro/:rw
                # suffix means "this is a mount", so a typo there is an error rather
                # than a prompt that silently reaches the model.
                set -l p $a
                set -l m rw
                set -l explicit 0
                switch $a
                    case '*:ro' '*:rw'
                        set p (string sub -e -3 -- $a)
                        set m (string sub -s -2 -- $a)
                        set explicit 1
                end
                if test -e $p
                    set -a extra_mounts (path resolve $p):$m
                else if test $explicit -eq 1
                    echo "ob: no such path to mount: $p" >&2
                    return 1
                else
                    set -a agent_argv $a
                end
        end
    end

    # claudebox only execs `<shell> -l` — no command/env passthrough. Write an
    # entry script under ~/.my-omp (mounted) that cds to the project and starts ompui.
    mkdir -p $omp_dir/run
    set -l entry $omp_dir/run/ob-entry.sh
    set -l envfile $omp_dir/run/ob-env.sh

    set -l mode agent
    if test $shell_mode -eq 1
        set mode shell
    end

    # One bash helper: write 0600 env snapshot + 0700 entry script with %q quoting.
    # Claudebox does not forward host env (only PATH/HOME/TERM/USER/SHELL).
    env \
        OB_MODE=$mode \
        OB_PROJECT=$project \
        OB_AGENT=$agent \
        OB_ENVFILE=$envfile \
        OB_ENTRY=$entry \
        bash -c '
set -euo pipefail

names=(
  OPENROUTER_API_KEY DEEPSEEK_API_KEY OPENAI_API_KEY ANTHROPIC_API_KEY
  XAI_API_KEY GROK_API_KEY MOONSHOT_API_KEY KIMI_API_KEY
  GEMINI_API_KEY GOOGLE_API_KEY GITHUB_TOKEN GH_TOKEN
)
{
  echo "# generated by ob — do not commit"
  # Belt-and-braces: bootstrap.ts sets this too, but pinning it here keeps
  # --shell mode and a bare `bun run src/main.ts` on the same config root.
  echo "export PI_CONFIG_DIR=.my-omp"
  for name in "${names[@]}"; do
    if [ -n "${!name+x}" ]; then
      printf "export %s=%q\n" "$name" "${!name}"
    fi
  done
} >"$OB_ENVFILE"
chmod 600 "$OB_ENVFILE"

{
  echo "#!/usr/bin/env bash"
  echo "set -euo pipefail"
  echo "# claudebox starts the entrypoint as: <path> -l"
  echo "while [ \$# -gt 0 ]; do"
  echo "  case \"\$1\" in -l|--login) shift ;; *) break ;; esac"
  echo "done"
  printf "source %q\n" "$OB_ENVFILE"
  printf "cd %q || exit 1\n" "$OB_PROJECT"
  if [ "$OB_MODE" = shell ]; then
    echo "exec \"\${SHELL:-/bin/sh}\" -l"
  else
    printf "exec bun run %q" "$OB_AGENT/src/bootstrap.ts"
    for a in "$@"; do
      printf " %q" "$a"
    done
    printf "\n"
  fi
} >"$OB_ENTRY"
chmod 700 "$OB_ENTRY"
' -- $agent_argv

    set -l cb_args --no-mount-home
    # Paths already claimed, so nothing gets mounted twice (runsc takes the last
    # spec for a destination, which would silently downgrade an rw mount to ro).
    set -l mounted
    # Agent tree (ompui + node_modules). Always mount so the entrypoint can run
    # even when $PWD is some other project.
    set -a cb_args --mount $agent
    set -a mounted $agent
    if test $project != $agent
        set -a cb_args --mount $project
        set -a mounted $project
    end
    # Auth, settings, sessions, models, and this entry script.
    set -a cb_args --mount $omp_dir
    set -a mounted $omp_dir
    # Extra paths named on the command line. Before the MCP dirs so that naming
    # one of those explicitly gets you rw instead of the default ro.
    for spec in $extra_mounts
        set -l p (string sub -e -3 -- $spec)
        if not contains -- $p $mounted
            set -a cb_args --mount $spec
            set -a mounted $p
        end
    end
    # Skip a missing dir rather than letting one moved MCP server kill the sandbox,
    # and skip one already mounted rw above (running `ob` from inside it).
    for d in $mcp_dirs
        if test -d $d; and not contains -- $d $mounted
            set -a cb_args --mount $d:ro
        end
    end

    # Title the tab for the duration; fish_title restores it at the next prompt.
    if isatty stdout
        printf '\e]2;ob %s\a' (basename $project)
    end

    # No --lan-range → pasta default: egress ok, RFC1918/link-local/loopback denied.
    # Deliberately not `exec`: exec'ing replaces this shell, so the terminal tab
    # dies with the sandbox and nothing ever updates the title again. Run it as a
    # child and let fish return to the prompt on exit.
    $claudebox_bin $cb_args $entry
end
