# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                 CachyOS Hyprland Configuration              ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

$mainMod = SUPER

plugin {
    hyprsplit {
        num_workspaces = 5
    }
}

# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                         Source Files                        ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
source = ~/dotfiles/.config/hypr-cachyos/config/animations.conf
source = ~/dotfiles/.config/hypr-cachyos/config/autostart.conf
source = ~/dotfiles/.config/hypr-cachyos/config/decorations.conf
source = ~/dotfiles/.config/hypr-cachyos/config/environment.conf
source = ~/dotfiles/.config/hypr-cachyos/config/input.conf
source = ~/dotfiles/.config/hypr-cachyos/config/keybinds.conf
source = ~/dotfiles/.config/hypr-cachyos/config/monitor.conf
source = ~/dotfiles/.config/hypr-cachyos/config/variables.conf
source = ~/dotfiles/.config/hypr-cachyos/config/windowrules.conf

# Modifying these configs can be done by creating a user defined config in the home directory, e.g.
## ~/.config/hypr/config/user-config.conf
#source = ~/.config/hypr/config/user-config.conf
